#:schema node_modules/@opennextjs/cloudflare/wrangler-schema.json

name = "agent-tinder"
account_id = "3f644644c8044a84ea233addb7da12fd"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets
assets = { directory = ".open-next/assets", binding = "ASSETS" }
